name: cuba_weather_dart_example
description: Example of Dart client for www.redcuba.cu weather API. Given a location in Cuba, if it is within the permitted locations, meteorological data on the location is obtained.
version: 0.1.0
homepage: https://github.com/leynier/cuba-weather-dart

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  cuba_weather_dart: ^0.1.0
