name: cuba_weather_dart
description: Dart client for www.redcuba.cu weather API. Given a location in Cuba, if it is within the permitted locations, meteorological data on the location is obtained.
version: 1.2.0
homepage: https://github.com/leynier/cuba-weather-dart

environment:
  sdk: ">=2.2.0 <3.0.0"

dependencies:
  http: ^0.12.0
  equatable: ^1.0.0
  test: ^1.11.0
  edit_distance: ^0.4.1

dev_dependencies:
