name: Dart CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build_on_ubuntu:

    runs-on: ubuntu-latest

    container:
      image:  google/dart:latest

    steps:
    - uses: actions/checkout@v1
    - name: Install dependencies
      run: pub get
    - name: Run tests
      run: pub run test
    - name: Publish
      run: pub publish

  build_on_windows:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v1
    - name: Install dependencies
      run: pub get
    - name: Run tests
      run: pub run test
    - name: Publish
      run: pub publish
